#!/usr/bin/env python3
"""SRT to ASS converter with bilingual subtitle support.

Handles both single-language and bilingual (English+Chinese) SRT files,
configures proper fonts for CJK text, and produces ASS files suitable for
ffmpeg's ass filter.

Usage:
    python srt-to-ass.py input.srt output.ass [--font-size N] [--font NAME]
"""

import argparse
import re
import sys


def parse_srt(path: str) -> list[dict]:
    """Parse SRT file into list of {index, start, end, lines} dicts."""
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()

    blocks = content.strip().split("\n\n")
    entries = []
    for block in blocks:
        lines = block.strip().split("\n")
        if len(lines) < 3:
            continue
        time_line = lines[1]
        text_lines = lines[2:]

        parts = time_line.split(" --> ")

        def parse_ts(ts: str) -> float:
            h, m, s = ts.split(":")
            return int(h) * 3600 + int(m) * 60 + float(s.replace(",", "."))

        entries.append({
            "start": parse_ts(parts[0]),
            "end": parse_ts(parts[1]),
            "lines": text_lines,
        })

    return sorted(entries, key=lambda x: x["start"])


def detect_bilingual(entries: list[dict]) -> bool:
    """Detect if this is a bilingual SRT (en line followed by zh line per entry)."""
    if not entries:
        return False
    sample = entries[:min(20, len(entries))]
    for e in sample:
        if len(e["lines"]) >= 2:
            en, zh = e["lines"][0], e["lines"][1]
            # If second line contains CJK chars and differs from first line
            if re.search(r"[一-鿿㐀-䶿]", zh) and en != zh:
                return True
    return False


def fmt_ass_time(seconds: float) -> str:
    """Format seconds to ASS timestamp H:MM:SS.cc"""
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = seconds % 60
    return f"{h}:{m:02d}:{s:05.2f}"


def generate_ass(entries: list[dict], is_bilingual: bool,
                 font_size: int = 20, font_name: str = "Arial") -> str:
    """Generate ASS content from parsed SRT entries."""
    if is_bilingual:
        font_size_en = max(font_size - 2, 14)
        font_size_zh = font_size
    else:
        font_size_en = font_size
        font_size_zh = font_size

    lines = []
    lines.append("[Script Info]")
    lines.append("; Generated by youtube-subtitle-translate skill")
    lines.append("ScriptType: v4.00+")
    lines.append("PlayResX: 1920")
    lines.append("PlayResY: 1080")
    lines.append("ScaledBorderAndShadow: yes")
    lines.append("YCbCr Matrix: None")
    lines.append("")
    lines.append("[V4+ Styles]")
    lines.append(
        f"Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
        f"OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
        f"ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
        f"Alignment, MarginL, MarginR, MarginV, Encoding"
    )
    if is_bilingual:
        lines.append(
            f"Style: Default,{font_name},{font_size_en},&H00FFFFFF,&H00FFFFFF,"
            f"&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,1,0,2,10,10,30,1"
        )
        lines.append(
            f"Style: Chinese,PingFang SC,{font_size_zh},&H00FFFFFF,&H00FFFFFF,"
            f"&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,1,0,2,10,10,50,1"
        )
    else:
        lines.append(
            f"Style: Default,{font_name},{font_size},&H00FFFFFF,&H00FFFFFF,"
            f"&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,1,0,2,10,10,30,1"
        )
    lines.append("")
    lines.append("[Events]")
    lines.append(
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, "
        "Effect, Text"
    )

    for entry in entries:
        start = fmt_ass_time(entry["start"])
        end = fmt_ass_time(entry["end"])
        text = entry["lines"]

        if is_bilingual and len(text) >= 2:
            en_line = text[0].replace("\n", "")
            zh_line = text[1].replace("\n", "")
            combined = f"{en_line}\\N{zh_line}"
        else:
            combined = "\\N".join(text).replace("\n", "\\N")

        # Escape ASS special chars
        combined = combined.replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}")

        lines.append(f"Dialogue: 0,{start},{end},Default,,0,0,0,,{combined}")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Convert SRT to ASS subtitles")
    parser.add_argument("input", help="Input SRT file path")
    parser.add_argument("output", help="Output ASS file path")
    parser.add_argument("--font-size", type=int, default=20, help="Base font size (default: 20)")
    parser.add_argument("--font", default="Arial", help="Font name for non-CJK text (default: Arial)")
    args = parser.parse_args()

    entries = parse_srt(args.input)
    if not entries:
        print(f"ERROR: No subtitle entries found in {args.input}", file=sys.stderr)
        sys.exit(1)

    is_bilingual = detect_bilingual(entries)
    print(f"Parsed {len(entries)} entries, bilingual={is_bilingual}", file=sys.stderr)

    # Validate: warn about abnormally long durations (>120s likely indicates
    # corrupted data from parallel agent processing)
    MAX_REASONABLE_DURATION = 120  # seconds
    long_entries = [e for e in entries if (e["end"] - e["start"]) > MAX_REASONABLE_DURATION]
    if long_entries:
        print(f"WARNING: {len(long_entries)} entries have duration > {MAX_REASONABLE_DURATION}s:", file=sys.stderr)
        for e in long_entries:
            dur = e["end"] - e["start"]
            print(f"  [{e['lines'][0][:50]}] {e['start']:.1f}-{e['end']:.1f} ({dur:.0f}s)", file=sys.stderr)
        # Auto-fix: cap unreasonably long durations at 6 seconds
        for e in long_entries:
            e["end"] = e["start"] + 6.0
        print(f"  Auto-fixed: capped all to 6s duration", file=sys.stderr)

    ass_content = generate_ass(entries, is_bilingual, args.font_size, args.font)

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(ass_content)

    print(f"Wrote {args.output} ({len(entries)} dialogue lines)", file=sys.stderr)


if __name__ == "__main__":
    main()
